import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Download, Printer } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/app/AppShell";
import { CitationCard, Panel, RiskBadge, axisProps, compactUSD, tooltipStyle } from "@/components/app/widgets";
import { Button } from "@/components/ui/button";
import { buildReports } from "@/services/reporting";
import type { Report, ReportChart } from "@/domain/types";
import { appConfig } from "@/config/app";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports — Multi-Agent Financial Intelligence" },
      { name: "description", content: "Executive, anomaly, vendor spend and monthly risk reports with evidence and citations." },
      { property: "og:title", content: "Reports — Multi-Agent Financial Intelligence" },
      { property: "og:description", content: "Print-ready financial operations reports generated from synthetic data." },
    ],
  }),
  component: ReportsPage,
});

const isCount = (c: ReportChart) => /transactions|anomalies/i.test(c.valueLabel);

function ChartView({ c }: { c: ReportChart }) {
  const fmt = (v: number) => (isCount(c) ? String(v) : compactUSD(v));
  return (
    <div className="rounded-md border border-border p-3">
      <h3 className="mb-2 text-xs font-semibold">{c.title}</h3>
      <div className="h-56"><ResponsiveContainer>
        {c.kind === "line" ? (
          <LineChart data={c.data}>
            <CartesianGrid stroke="var(--border)" vertical={false} />
            <XAxis dataKey="name" {...axisProps} />
            <YAxis tickFormatter={fmt} width={52} {...axisProps} />
            <Tooltip {...tooltipStyle} formatter={(v: number) => fmt(v)} />
            <Line dataKey="value" name={c.valueLabel} stroke="var(--chart-1)" strokeWidth={2} dot={{ r: 3 }} />
          </LineChart>
        ) : (
          <BarChart data={c.data}>
            <CartesianGrid stroke="var(--border)" vertical={false} />
            <XAxis dataKey="name" {...axisProps} interval={0} angle={c.data.length > 4 ? -30 : 0} textAnchor={c.data.length > 4 ? "end" : "middle"} height={c.data.length > 4 ? 60 : 30} />
            <YAxis tickFormatter={fmt} width={52} {...axisProps} />
            <Tooltip {...tooltipStyle} formatter={(v: number) => fmt(v)} />
            {c.value2Label && <Legend wrapperStyle={{ fontSize: 12 }} />}
            <Bar dataKey="value" name={c.valueLabel} fill="var(--chart-1)" radius={[3, 3, 0, 0]} />
            {c.value2Label && <Bar dataKey="value2" name={c.value2Label} fill="var(--chart-5)" radius={[3, 3, 0, 0]} />}
          </BarChart>
        )}
      </ResponsiveContainer></div>
    </div>
  );
}

function toMarkdown(r: Report) {
  return [
    `# ${r.title}`, `Period: ${r.period}`, "", `> ${appConfig.disclaimer}`, "", `## Summary`, r.headline, "",
    `## Key Findings`, ...r.findings.map((f) => `- ${f}`), "",
    `## Evidence`, ...r.evidence.map((e) => `- ${e.label}: ${e.value}`), "",
    `## Risk Assessment`, `Level: ${r.risk.level} (score ${r.risk.score})`, ...r.risk.indicators.map((i) => `- ${i}`), "",
    `## Recommended Next Steps`, ...r.nextSteps.map((s, i) => `${i + 1}. ${s}`), "",
    `## Sources`, ...r.citations.map((c, i) => `[${i + 1}] ${c.docTitle}, ${c.sectionLabel} — "${c.excerpt}"`),
  ].join("\n");
}

function ReportsPage() {
  const reports = useMemo(() => buildReports(), []);
  const [id, setId] = useState<Report["id"]>("executive");
  const r = reports.find((x) => x.id === id)!;

  function download() {
    const blob = new Blob([toMarkdown(r)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${r.id}-report-${appConfig.currentMonth}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Structured, evidence-backed reports generated by the Report Writer agent."
        actions={<>
          <Button variant="outline" onClick={() => window.print()}><Printer /> Print / PDF</Button>
          <Button onClick={download}><Download /> Download .md</Button>
        </>}
      />
      <div role="tablist" aria-label="Reports" className="no-print mb-4 grid grid-cols-2 gap-2 lg:grid-cols-4">
        {reports.map((x) => (
          <button key={x.id} role="tab" aria-selected={x.id === id} type="button" onClick={() => setId(x.id)}
            className={cn("surface p-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", x.id === id ? "border-primary/60" : "hover:border-primary/30")}>
            <div className="text-sm font-semibold">{x.title}</div>
            <div className="mt-1 text-xs text-muted-foreground">{x.description}</div>
          </button>
        ))}
      </div>

      <article className="print-area space-y-4" role="tabpanel">
        <Panel>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <div className="text-xs uppercase tracking-wider text-muted-foreground">{r.period} · Synthetic data</div>
              <h2 className="mt-1 text-xl font-semibold">{r.title}</h2>
              <p className="mt-2 max-w-3xl text-sm">{r.headline}</p>
            </div>
            <RiskBadge level={r.risk.level} score={r.risk.score} />
          </div>
          <dl className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">
            {r.evidence.map((e) => (
              <div key={e.label} className="rounded-md border border-border bg-muted/40 p-2.5">
                <dt className="truncate text-[11px] text-muted-foreground">{e.label}</dt>
                <dd className="tabular text-sm font-semibold">{e.value}</dd>
              </div>
            ))}
          </dl>
        </Panel>
        <div className="grid gap-4 lg:grid-cols-2">{r.charts.map((c) => <ChartView key={c.title} c={c} />)}</div>
        <div className="grid gap-4 lg:grid-cols-2">
          <Panel title="Key findings">
            <ul className="list-disc space-y-1.5 pl-5 text-sm marker:text-primary">{r.findings.map((f, i) => <li key={i}>{f}</li>)}</ul>
          </Panel>
          <Panel title="Risk indicators & next steps">
            <ul className="space-y-1 text-sm">{r.risk.indicators.map((x, i) => <li key={i}>• {x}</li>)}</ul>
            <h3 className="mb-1 mt-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Recommended next steps</h3>
            <ol className="list-decimal space-y-1 pl-5 text-sm">{r.nextSteps.map((s) => <li key={s}>{s}</li>)}</ol>
          </Panel>
        </div>
        <Panel title="Sources">
          {r.citations.length ? (
            <div className="grid gap-2 md:grid-cols-3">{r.citations.map((c, i) => <CitationCard key={c.docId + c.sectionLabel} c={c} index={i} />)}</div>
          ) : <p className="text-sm text-muted-foreground">No supporting document was found.</p>}
        </Panel>
      </article>
    </div>
  );
}
